services:
  n8n:
    container_name: n8nserver
    image: docker.n8n.io/n8nio/n8n
    environment:
      - GENERIC_TIMEZONE="Australia/Melbourne"
      - TZ="Australia/Melbourne"
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"

  prefect:
    image: prefecthq/prefect:3-latest    
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0      
    command: prefect server start
    volumes:
      - prefect_data:/root/.prefect
    ports:
      - "4200:4200"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:4200/api/health')"]
      interval: 5s
      timeout: 30s
      retries: 3

  prefect-worker:
    image: prefecthq/prefect:3-latest
    depends_on:
      prefect:
        condition: service_healthy
    environment:
      PREFECT_API_URL: http://prefect:4200/api
    command: prefect worker start --pool local-pool

volumes:  
  n8n_data: {}
  prefect_data: {}  
    